name: API Automation Workflow
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: write
  id-token: write

jobs:

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'



        run: ./gradlew clean test

      - name: Archive test results
        uses: actions/upload-artifact@v4.6.2
        if: always()
        with: